/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retsult_managment_portal;

import javax.swing.JOptionPane;

/**
 *
 * @author rohnk
 */
public class adminIndex extends javax.swing.JFrame {

    /**
     * Creates new form adminIndex
     */
    public adminIndex() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usenameLable = new javax.swing.JLabel();
        passwordLable = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usenameLable.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        usenameLable.setText("Username");
        usenameLable.setToolTipText("");
        usenameLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(usenameLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 174, 123, 35));

        passwordLable.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        passwordLable.setText("Password");
        passwordLable.setPreferredSize(new java.awt.Dimension(150, 45));
        getContentPane().add(passwordLable, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 237, 123, 36));

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 174, 178, 35));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 238, 178, 35));

        login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons&bgs/icons8-login-16.png"))); // NOI18N
        login.setText("Login");
        login.setMaximumSize(new java.awt.Dimension(84, 31));
        login.setMinimumSize(new java.awt.Dimension(84, 31));
        login.setPreferredSize(new java.awt.Dimension(84, 31));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 291, -1, 30));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons&bgs/icons8-back-24.png"))); // NOI18N
        back.setText("Back");
        back.setMinimumSize(new java.awt.Dimension(84, 31));
        back.setPreferredSize(new java.awt.Dimension(84, 31));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 291, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons&bgs/admin_bgjpg.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String Username = username.getText();
        String Password = password.getText();
        
        if(Username.equals("admin") && Password.equals("pass")){
            setVisible(false);
            new adminHome().setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null , "Incorrect Username or Password!");
        }
        
    }//GEN-LAST:event_loginActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new index().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLable;
    private javax.swing.JLabel usenameLable;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
